# Generated by Django 4.2.7 on 2023-12-13 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='time',
        ),
        migrations.AddField(
            model_name='contact',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 13, 8, 55, 28, 331378, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
